title: "Jixuan Leng"
description: "Personal website for Jixuan Leng, focused on efficient and reliable foundation models."
repository: "SeanLeng1/SeanLeng1.github.io"
url: "https://jixuanleng.com"
baseurl: ""
lang: "en"
timezone: America/Los_Angeles

include:
  - _pages

exclude:
  - legacy
  - docs
  - vendor
  - node_modules
  - _site

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-scholar

scholar:
  last_name: Leng
  first_name: Jixuan
  style: apa
  locale: en
  sort_by: year, month
  order: descending
  source: /_bibliography/
  bibliography: papers.bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  query: "@*"
